### ISSUE TITLE
Bugs - show & delete buttons

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#67]
Hi,
I find some bugs..
1) Show button bug - do not see the button http://prntscr.com/7wt4up
2) Delete button bug - buttons disappear http://prntscr.com/7wt61e and appear elsewhere http://prntscr.com/7wt6bp

**Comment by serverfire** [comment]
@Globax  Could you upload it somewhere to i can see what happen with buttons

**Comment by Globax** [comment]
@serverfire 
https://sendvid.com/6ks7h47g

**Comment by serverfire** [comment]
@Globax Could you tell me which browser you are using and which version

**Comment by Globax** [comment]
@serverfire 
Chromium: Version 41.0.2260.0 (64-bit)
On Safari: Version 8.0.7 (10600.7.12) - only can't see Show button.

**Comment by serverfire** [comment]
@Globax  Could do a test for me ?
change css file : public\packages\serverfireteam\panel\css\styles.css

line 7794
```css
/*-------------- zofe rapyd => crud --------------------*/
.table a {
  text-decoration: none;
  transition: all ease 250ms;
}
.table a:hover {
  transform: scale(1.2, 1.2);
  -webkit-transform: scale(1.2, 1.2);
}
.table .icomoon {
  font-size: 22px;
  text-decoration: none;
  transition: all  ease 250ms;
}
.table tr {
  transition: all ease  250ms;
}
.table tr:nth-child(even) {
  background: #f5f5f5;
}
.table tr:hover {
  border-color: #777;
}
.btn {
  transition: all ease 250ms;
}
```

too :

```css
/*-------------- zofe rapyd => crud --------------------*/
.table a {
  text-decoration: none;
}
.table .icomoon {
  font-size: 22px;
  text-decoration: none;
}
.table tr:nth-child(even) {
  background: #f5f5f5;
}
.table tr:hover {
  border-color: #777;
}

```

and tell if it fixed with that
